### PR TITLE
Update countly.cpp

### PR DESCRIPTION
**Pull request by liangwu**
fix thread 0(ui) hung when exit.

### CODE REVIEW

**Comment by LVMBDV** [comment]
I'm not so sure with this one. This change basically divides the update loop's wait period into 10 pieces and checks (without locking the Countly object's mutex) if a stop command is given. This essentially shortens the response time of a stop command without changing the frequency of session updates, which is clever, but I feel like we could do it in a cleaner way by having a separate mechanism for timing session updates in the loop and shortening the loop wait time so it's more responsive.

Just to confirm, your thread doesn't hang permanently after exit, it hangs about 3 seconds because `COUNTLY_KEEPALIVE_INTERVAL` is set to `3000`, right?

**Comment by liangwu** [comment]
yes, it is.

I agree with you, a WAIT CONDITION with "timeout" may be a better solution.

Ata Kuyumcu <notifications@github.com> 于2020年11月23日周一 下午12:13写道：

**Comment by liangwu** [comment]
> I'm not so sure with this one. This change basically divides the update loop's wait period into 10 pieces and checks (without locking the Countly object's mutex) if a stop command is given. This essentially shortens the response time of a stop command without changing the frequency of session updates, which is clever, but I feel like we could do it in a cleaner way by having a separate mechanism for timing session updates in the loop and shortening the loop wait time so it's more responsive.
> 
> Just to confirm, your thread doesn't hang permanently after exit, it hangs about 3 seconds because `COUNTLY_KEEPALIVE_INTERVAL` is set to `3000`, right?

endsession() in stop method leads to ui hung too

**Comment by ArtursKadikis** [comment]
Closing this due to the issues raised in the initial response. We might reassess this at a later point.

**Pull request closed without merging**
