### PR TITLE
Extract constants header

### PR DESCRIPTION
**Pull request by borgbyte**
Seeking feedback for splitting the header. This is the first of a series of changes. 

See https://github.com/libgit2/libgit2/blob/main/include/git2.h as an example of how the main header could look like.

### CODE REVIEW

**Comment by ArtursKadikis** [comment]
What would be the main targeted benefit for this?

**Comment by ArtursKadikis** [comment]
In this PR also only 2 of the extracted 6 values are related to versioning.

**Comment by ArtursKadikis** [comment]
I think in this case "constants" seem like a better name for the extracted header file

**Comment by ArtursKadikis** [comment]
"COUNTLY_VERSION_HPP_" would also have to be updated

**Comment by borgbyte** [comment]
Done.

**Review by ArtursKadikis — APPROVED** [review]

**Pull request merged**
