### PR TITLE
[SDK 646] Added new public method to change device id

### PR DESCRIPTION
**Pull request by ZahidZafar**

### CODE REVIEW

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
No new public methods should be added. The only call to change the device ID should be "setDeviceID".

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
Wrong changelog entry.

The "if (!began_session) {" checks should be moved out of "_changeDeviceIdWithMerge" and "_changeDeviceIdWithoutMerge".

The check for if the new and old device ID are the same should also be moved outside of those calls.

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
The following call had to be moved outside of their calls and not removed:
'
The "if (!began_session) {" checks should be moved out of "_changeDeviceIdWithMerge" and "_changeDeviceIdWithoutMerge".

The changelog entry should be corrected

The check for if the new and old device ID are the same should also be moved outside of those calls.
'

**Comment by ZahidZafar** [comment]
They are already there.
If you want to make them simple and refactor let me know.
image

**Pull request merged**
